// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types
export const SET_TIERLISTS = 'SET_TIERLISTS';
export const SET_TIERLIST = 'SET_TIERLIST';
export const LIKE_TIERLIST = 'LIKE_TIERLIST';
export const UNLIKE_TIERLIST = 'UNLIKE_TIERLIST';
export const DELETE_TIERLIST = 'DELETE_TIERLIST';
export const POST_TIERLIST = 'POST_TIERLIST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const UPDATE_TIERLISTS_INFO = 'UPDATE_TIERLISTS_INFO';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_WITH_TIERLISTS = 'SET_CATEGORIES_WITH_TIERLISTS';
export const SET_CATEGORY = 'SET_CATEGORY';
export const RESET_VIEW_CATEGORY = 'RESET_VIEW_CATEGORY';
export const RESET_CATEGORIES = 'RESET_CATEGORIES';
export const SET_TIER_ITEMS = 'SET_TIER_ITEMS';
export const SET_USER_TIER_ITEMS = 'SET_USER_TIER_ITEMS';
export const RESET_VIEW_TIER_ITEMS = 'RESET_VIEW_TIER_ITEMS';
export const DELETE_TIER_ITEM = 'DELETE_TIER_ITEM';
export const POST_TIER_ITEM = 'POST_TIER_ITEM';
export const UPDATE_TIER_ITEM = 'UPDATE_TIER_ITEM';
export const SET_VIEW_TIER_LIST = 'SET_VIEW_TIER_LIST';
export const ADD_TO_VIEW_TIER_LIST = 'ADD_TO_VIEW_TIER_LIST';
export const DELETE_FROM_VIEW_TIER_LIST = 'DELETE_FROM_VIEW_TIER_LIST';
export const SORT_VIEW_TIER_LIST = 'SORT_VIEW_TIER_LIST';