// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types
export const SET_TIERLISTS = 'SET_TIERLISTS';
export const SET_TIERLIST = 'SET_TIERLIST';
export const LIKE_TIERLIST = 'LIKE_TIERLIST';
export const UNLIKE_TIERLIST = 'UNLIKE_TIERLIST';
export const DELETE_TIERLIST = 'DELETE_TIERLIST';
export const POST_TIERLIST = 'POST_TIERLIST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const UPDATE_TIERLISTS_IMG = 'UPDATE_TIERLISTS_IMG';
export const UPDATE_TIERLISTS_INFO = 'UPDATE_TIERLISTS_INFO';